connect firebase to the project + added functioanilty to write data in the data base
Alez05/my-portfolio-v2 pull request #33
Opened 2024-09-03 23:35 UTC by Alez05

Fixes #32

2024-09-03 23:59 UTC, marianzburlea requested changes

2024-09-03 23:59 UTC, marianzburlea commented on .gitignore
> +
if you also use `.env.local` you want to add it too
otherwise ignore

2024-09-03 23:59 UTC, marianzburlea commented on src/app/server/firebase.server.ts
> +export const writeData = async (table = '', date={}, id ='' ) => {
date -> `data`
or `info`

2024-09-04 00:20 UTC, Alez05 commented on .gitignore
> +
I only made use of .env so far

2024-09-04 00:22 UTC, Alez05 commented on src/app/server/firebase.server.ts
> +export const writeData = async (table = '', date={}, id ='' ) => {
fixed;

2024-09-04 05:15 UTC, florin-bizgan approved these changes
Looks good

2024-09-04 07:33 UTC, merged